--liquibase formatted sql

-- changeset dgaponov99:001-init
create table item
(
    item_id     bigint       not null primary key,
    description varchar(500) not null,
    price       bigint       not null,
    title       varchar(255) not null
);

create table cart_item
(
    item_id bigint  not null primary key,
    count   integer not null
);

create table orders
(
    order_id   bigint generated by default as identity primary key,
    order_date timestamp not null
);

create table order_item
(
    id       bigserial primary key,
    item_id  bigint  not null references item,
    order_id bigint  not null references orders,
    count    integer not null,

    unique (order_id, item_id)
);

-- changeset dgaponov99:002-users
create table users
(
    user_id    bigint generated by default as identity primary key,
    username   varchar(255) not null unique,
    password   varchar(255) not null,
    account_id bigint       not null,
    disabled   boolean      not null default false
);

-- changeset dgaponov99:003-userCarts
drop table cart_item;
truncate table orders cascade;

create table cart_item
(
    id      bigserial primary key,
    user_id bigint  not null references users,
    item_id bigint  not null references item,
    count   integer not null,

    unique (user_id, item_id)
);

alter table orders
    add column user_id bigint not null references users;

alter table order_item
    add column unit_price bigint not null;

