--liquibase formatted sql

-- changeset dgaponov99:001-init
create table item
(
    item_id     bigint       not null primary key,
    description varchar(500) not null,
    price       bigint       not null,
    title       varchar(255) not null
);

create table cart_item
(
    item_id bigint  not null primary key,
    count   integer not null
);

create table orders
(
    order_id   bigint generated by default as identity primary key,
    order_date timestamp not null
);

create table order_item
(
    id bigserial primary key,
    item_id  bigint  not null references item,
    order_id bigint  not null references orders,
    count    integer not null,

    unique(order_id, item_id)
);
