--liquibase formatted sql

-- changeset dgaponov99:001-init
create table account
(
    account_id bigint generated by default as identity primary key,
    balance    bigint not null default 0 check ( balance >= 0 )
)
