spring.application.name=practicum-my-market-app

server.port=80

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/practicum_my_market
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

spring.liquibase.url=jdbc:postgresql://localhost:5432/practicum_my_market
spring.liquibase.user=postgres
spring.liquibase.password=postgres

spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=app
spring.security.oauth2.client.registration.keycloak.client-secret=HhWYncsSxb0cQcCu1x1D8EMmwRYMcss0
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak.scope=openid

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8180/realms/my-market

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %level [%thread] [%logger{36}:%L] %msg %n
